Change adherent interests
EnMarche/en-marche.fr pull request #5949
Opened 2021-06-22 13:08 UTC by Remg

2021-06-22 13:35 UTC, illusionOfParadise approved these changes

2021-06-22 17:50 UTC, victorcohenfr requested changes
Sauf erreur, il manque : 
- `Villes et quartiers`
- `Famille`

2021-06-23 11:48 UTC, victorcohenfr approved these changes

2021-06-23 14:17 UTC, ottaviano approved these changes

2021-06-23 14:35 UTC, merged